MACOSX_DEPLOYMENT_TARGET:
- '10.9'
MACOSX_SDK_VERSION:
- '10.9'
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cross_target_platform:
- win-64
macos_machine:
- x86_64-apple-darwin13.4.0
rust_arch:
- x86_64-pc-windows-msvc
rust_arch_env:
- X86_64_PC_WINDOWS_MSVC
rust_arch_env_build:
- X86_64_APPLE_DARWIN
rust_default_cc:
- clang-cl
rust_default_cc_build:
- x86_64-apple-darwin13.4.0-clang
target_platform:
- osx-64
version:
- 1.73.0
zip_keys:
- - channel_sources
  - channel_targets
  - version
- - cross_target_platform
  - rust_arch
  - rust_arch_env
  - rust_default_cc
  - MACOSX_SDK_VERSION
  - MACOSX_DEPLOYMENT_TARGET
